### ISSUE TITLE
Exception handling for Neo4j errors

### ISSUE THREAD

**Issue by onyame** [DLR-SC/gitlab2prov#19]
`ValueError: invalid literal for int() with base 10: '7474:7687'`

if config.ini contains

```
[NEO4J]
host = localhost:7474
```

**Comment by cdboer** [comment]
Excerpt from the relevant code of prov-db-connector. 
```python
def connect(self, authentication_options):
        """
        The connect method to create a new instance of the db_driver
        :param authentication_options: Username, password and host
        :return: None
        :rtype: None
        :raises: InvalidOptionsException
        """
        if authentication_options is None:
            raise InvalidOptionsException()

        user_name = authentication_options.get("user_name")
        user_pass = authentication_options.get("user_password")
        host = authentication_options.get("host")

        if user_name is None or user_pass is None or host is None:
            raise InvalidOptionsException()

        try:
            self.driver = GraphDatabase.driver("bolt://{}".format(host), auth=basic_auth(user_name, user_pass))

        except SessionError as e:
            raise InvalidOptionsException(e)

        self._create_session()
```
`host` has to be the network location part of the url. 
As in `<scheme>://<net_loc>/<path>;<params>?<query>#<fragment>` as described by [RFC 1808](https://tools.ietf.org/html/rfc1808.html)

There are some errors that can be avoided by correcting the entered host and some that can't and should be catched. For example, if a user enters something that looks like a url, the network location part can be parsed from it and tried as host. If this raises an exception we should catch it and raise one of our own with the hint that the host ist malformed. If the host does not look like a url we can simply try it and catch raised exceptions as described.

**Comment by onyame** [comment]
Another error:

```
Traceback (most recent call last):
  File "gitlab2prov.py", line 75, in <module>
    main(args.provn, args.neo4j)
  File "gitlab2prov.py", line 67, in main
    prov_api.save_document(document)
  File "/Users/onyame/opt/anaconda3/envs/gitlab2prov/lib/python3.7/site-packages/provdbconnector/prov_db.py", line 165, in save_document
    self.save_bundle(prov_bundle=bundle)
  File "/Users/onyame/opt/anaconda3/envs/gitlab2prov/lib/python3.7/site-packages/provdbconnector/prov_db.py", line 481, in save_bundle
    return self._save_bundle_internal(prov_bundle)
  File "/Users/onyame/opt/anaconda3/envs/gitlab2prov/lib/python3.7/site-packages/provdbconnector/prov_db.py", line 503, in _save_bundle_internal
    self.save_relation(relation, bundle_id)
  File "/Users/onyame/opt/anaconda3/envs/gitlab2prov/lib/python3.7/site-packages/provdbconnector/prov_db.py", line 563, in save_relation
    self.save_element(prov_element=from_type_cls(prov_relation.bundle, identifier=from_qualified_name), bundle_id=bundle_id)
  File "/Users/onyame/opt/anaconda3/envs/gitlab2prov/lib/python3.7/site-packages/provdbconnector/prov_db.py", line 246, in save_element
    self._create_bundle_association([prov_element], prov_element.bundle.identifier)
  File "/Users/onyame/opt/anaconda3/envs/gitlab2prov/lib/python3.7/site-packages/provdbconnector/prov_db.py", line 600, in _create_bundle_association
    self.save_bundle(to_bundle) # Save the empty bundle to create the bundle entity if necessary
  File "/Users/onyame/opt/anaconda3/envs/gitlab2prov/lib/python3.7/site-packages/provdbconnector/prov_db.py", line 479, in save_bundle
    self.save_element(prov_element=bundle_record)
  File "/Users/onyame/opt/anaconda3/envs/gitlab2prov/lib/python3.7/site-packages/provdbconnector/prov_db.py", line 242, in save_element
    self._adapter.save_element(attributes=attributes, metadata=metadata)
  File "/Users/onyame/opt/anaconda3/envs/gitlab2prov/lib/python3.7/site-packages/provdbconnector/db_adapters/neo4j/neo4jadapter.py", line 225, in save_element
    other=other_db_attribute_keys, all=db_attributes))
  File "/Users/onyame/opt/anaconda3/envs/gitlab2prov/lib/python3.7/site-packages/neo4j/v1/api.py", line 573, in __exit__
    self.close()
  File "/Users/onyame/opt/anaconda3/envs/gitlab2prov/lib/python3.7/site-packages/neo4j/v1/api.py", line 650, in close
    self.session.commit_transaction()
  File "/Users/onyame/opt/anaconda3/envs/gitlab2prov/lib/python3.7/site-packages/neo4j/v1/api.py", line 437, in commit_transaction
    result.consume()
  File "/Users/onyame/opt/anaconda3/envs/gitlab2prov/lib/python3.7/site-packages/neo4j/v1/api.py", line 754, in consume
    for _ in self:
  File "/Users/onyame/opt/anaconda3/envs/gitlab2prov/lib/python3.7/site-packages/neo4j/v1/api.py", line 736, in records
    self._session.fetch()
  File "/Users/onyame/opt/anaconda3/envs/gitlab2prov/lib/python3.7/site-packages/neo4j/v1/api.py", line 347, in fetch
    detail_count, _ = self._connection.fetch()
  File "/Users/onyame/opt/anaconda3/envs/gitlab2prov/lib/python3.7/site-packages/neo4j/bolt/connection.py", line 287, in fetch
    return self._fetch()
  File "/Users/onyame/opt/anaconda3/envs/gitlab2prov/lib/python3.7/site-packages/neo4j/bolt/connection.py", line 327, in _fetch
    response.on_failure(summary_metadata or {})
  File "/Users/onyame/opt/anaconda3/envs/gitlab2prov/lib/python3.7/site-packages/neo4j/v1/result.py", line 70, in on_failure
    raise CypherError.hydrate(**metadata)
neo4j.exceptions.DatabaseError: Could not append transaction representation to log

```

**Comment by onyame** [comment]
Support for Neo4j was removed.
