### ISSUE TITLE
ModuleNotFoundError: No module named 'click'

### ISSUE THREAD

**Issue by daniel-mohr** [DLR-SC/gitlab2prov#87]
**Describe the bug**

Installation in a minimal system is not possible as described:

```sh
$ gitlab2prov
Traceback (most recent call last):
  File "/usr/local/bin/gitlab2prov", line 5, in <module>
    from gitlab2prov.entrypoints.cli import cli
  File "/usr/local/lib/python3.10/dist-packages/gitlab2prov/entrypoints/cli.py", line 5, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

**To Reproduce**
Run in docker container `ubuntu:latest`:

```sh
$ apt-get update
...
$ DEBIAN_FRONTEND="noninteractive" apt-get install --no-install-recommends -q -y python3-pip
...
$ pip install gitlab2prov
Collecting gitlab2prov
  Downloading gitlab2prov-2.0.0-py3-none-any.whl (33 kB)
...
$ gitlab2prov
Traceback (most recent call last):
  File "/usr/local/bin/gitlab2prov", line 5, in <module>
    from gitlab2prov.entrypoints.cli import cli
  File "/usr/local/lib/python3.10/dist-packages/gitlab2prov/entrypoints/cli.py", line 5, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

**Expected behavior**

`click` should be mentioined as dependency.

**Comment by daniel-mohr** [comment]
`git` is also missing -- but is not a python dependency.

The following works  in a docker container `ubuntu:latest`:

```sh
$ apt-get update
$ DEBIAN_FRONTEND="noninteractive" apt-get install --no-install-recommends -q -y python3-pip python3-click git
...
$ pip install gitlab2prov
Collecting gitlab2prov
  Downloading gitlab2prov-2.0.0-py3-none-any.whl (33 kB)
...
$ gitlab2prov
Usage: gitlab2prov [OPTIONS] COMMAND1 [ARGS]... [COMMAND2 [ARGS]...]...
...
```
